src/formio/base.ts, test-d/formio/base.test-d.ts
Hopefully this works and it can avoid the derived `keyof Object` from composed types. I suspect this is because the intersection is treated as an object literal and not a interface.
(formio-builder gets complaints about `constructor` not being assignable to a literals union)
=> :recycle: Refactor multiple type into interfaces

src/formio/base.ts, src/formio/components/content.ts, src/formio/components/date.ts, src/formio/components/datetime.ts, src/formio/components/email.ts, src/formio/components/number.ts, src/formio/components/textfield.ts, src/formio/i18n.ts, test-d/formio/components/content.test-d.ts, test-d/formio/components/date.test-d.ts, test-d/formio/components/datetime.test-d.ts, test-d/formio/components/email.test-d.ts, test-d/formio/components/number.test-d.ts, test-d/formio/components/textfield.test-d.ts
Part of open-formulieren/open-forms#2958
This is a :boom: breaking change.
Rather than storing translations on the entire form definition, we will now track them on the component definition itself. This results in what was internal API/implementation detail to become public API, and the types for this representation are now updated.
We store translations in openForms.translations for each component, which itself is a mapping of
language code to a mapping of translations. Such a translation mapping has the translatable properties (of the component) as key and the translation as
value.
=> Change types for component translation storage

src/formio/components/file.ts, src/formio/components/index.ts, src/formio/index.ts, test-d/formio/components/file.test-d.ts
Partly closes  #2
This one is special, even in the case for 'multiple: false', the value is an array with only a single allowed item.
upstream Form.io file component allows many more upload targets, but we only support uploading to our own backend API. The upload configuration is generated and set dynamically by the backend, so that host names are not persisted in the JSON configuration.
=> Implement type definition for file upload component

README.md, src/formio/common.ts, src/formio/components/checkbox.ts, src/formio/components/email.ts, src/formio/components/index.ts, src/formio/components/radio.ts, src/formio/components/selectboxes.ts, src/formio/index.ts, src/types.ts, test-d/formio/components/checkbox.test-d.ts, test-d/formio/components/email.test-d.ts, test-d/formio/components/radio.test-d.ts, test-d/formio/components/selectboxes.test-d.ts
=> ✨ [#2] Implement types for several components

src/formio/components/currency.ts, test-d/formio/components/currency.test-d.ts
As discussed: https://github.com/open-formulieren/formio-builder/pull/50#discussion_r1386162318
=> 🐛 `currency` is not multiple capable

src/formio/components/bsn.ts, src/formio/components/index.ts, src/formio/index.ts, test-d/formio/components/bsn.test-d.ts
=> ✨ [#2] Implement types for `bsn`

src/formio/components/index.ts, src/formio/components/select.ts, src/formio/index.ts, test-d/formio/components/select.test-d.ts
Basically the same as selectboxes, but different value structure and multiple capable.
=> ✨ [#2] Implement types for `select`

src/formio/base.ts
We don't use it an it's typed as any anyway, so it's not very useful.
=> :fire: Blacklist 'widget' property

src/formio/components/columns.ts, src/formio/components/index.ts, src/formio/index.ts, test-d/formio/components/columns.test-d.ts
=> :sparkles: [#2] Implement columns component schema type

src/formio/components/editgrid.ts, src/formio/components/index.ts, src/formio/index.ts, test-d/formio/components/editgrid.test-d.ts
=> Implement types for editgrid component

src/formio/components/index.ts, src/formio/components/signature.ts, src/formio/index.ts, test-d/formio/components/signature.test-d.ts
=> Implement types for signature component

package-lock.json, package.json, src/formio/components/currency.ts, src/formio/components/number.ts, test-d/formio/components/currency.test-d.ts, test-d/formio/components/number.test-d.ts
Semantically this makes sense, and it's also what Formio uses as defaults when creating instances of those components.
Part of https://github.com/open-formulieren/formio-builder/issues/105
=> :bug: Allow null for currency/number components

src/formio/components/date.ts, src/formio/components/datetime.ts, src/formio/dates.ts, test-d/formio/components/date.test-d.ts, test-d/formio/components/datetime.test-d.ts
Fixes https://github.com/open-formulieren/open-forms/issues/3755
Related to https://github.com/open-formulieren/open-forms/issues/3755 where the widget needs to have a configuration option set so that invalid values are not automatically removed from the widget
=> :sparkles: Add the types for the Flatpickr custom options for the widget

src/formio/base.ts
Partly closes open-formulieren/open-forms#3922
null values are okay-ish in the Javascript code, but cause constraint errors when the component is used to populate a FormVariable in the backend which does not allow NULL values.
=> Disallow null values for prefill plugin or attribute

src/formio/components/textarea.ts, src/formio/components/textfield.ts
Partly closes open-formulieren/open-forms#4362
It is unused and too complex with 'multiple: true' cases, causing crashes in the admin interface.
=> Remove support for defaultValue translations

src/formio/components/addressNL.ts, test-d/formio/components/addressNL.test-d.ts
Partly fixes https://github.com/open-formulieren/open-forms/issues/4423
`layout` property was added in order to be able to choose between `singleColumn` or `doubleColumn` for the rendering of the `addressNL` component
=> [OF#4423] Add layout property to addressnl

src/formio/components/addressNL.ts
partially closes open-formulieren/open-forms#4420
=> :sparkles: [open-formulieren/open-forms#4420] AddressNL component validation

src/formio/base.ts, src/formio/components/addressNL.ts
todo clean commit msgs
to allow Validate.useManageValidatorsTranslations typing to be correct in the formio builder
=> :bug: [open-formulieren/open-forms#4420] Fix AddressNL validation type

src/formio/base.ts, src/formio/components/addressNL.ts, src/formio/components/date.ts, src/formio/components/datetime.ts, src/formio/components/email.ts, src/formio/components/radio.ts, src/formio/components/select.ts, src/formio/components/selectboxes.ts, src/formio/util.ts, test-d/formio/components/email.test-d.ts
Partially closes open-formulieren/open-forms#4542
* Refactored some typing utilities
* Used refactor to define email component extension `requireVerification`, which we'll expose in the formio builder after this is merged.
I checked that formio-builder still builds with `npm pack` and installing the tarball locally.
=> Add type definition to support e-mail verification

src/formio/components/file.ts, src/formio/components/index.ts, src/formio/components/softRequiredErrors.ts, src/formio/index.ts, test-d/formio/components/file.test-d.ts, test-d/formio/components/softRequiredErrors.test-d.ts
Partly closes open-formulieren/open-forms#4546
Added the type definitions for the extension on the file components and the new component to display 'validation errors'.
=> Soft required validation

src/formio/components/productPrice.ts, test-d/formio/components/productPrice.test-d.ts
Removes the product attribute as it will be set on the form instead of in the component.
=> [maykinmedia/open-producten#24] remove product attribute from Product

src/formio/components/number.ts
Partly solves open-formulieren/open-forms#4813
Added the prefillConfig to the number component allows prefill configuration on number fields
=> Adding PrefillConfig to BaseNumberComponentSchema

src/formio/components/map.ts
Part of open-formulieren/open-forms#2173
Updated the MapComponentSchema for the kaartmateriaal background changes.
Added `backgroundIdentifier` as property to MapComponentSchema
=> Updated MapComponentSchema for kaartmateriaal background feature

src/formio/components/map.ts
Part of open-formulieren/open-forms#2177
The interactions are base on the leaflet draw options: https://leaflet.github.io/Leaflet.draw/docs/leaflet-draw-latest.html#drawoptions.
Leaflet offers two more options: rectangle and circlemarker. Both seem not very useful (circlemarker being a weird mix of marker and circle, with less precision and flexibility, and rectangle just being weird..)
=> Add interaction property to component

src/formio/common.ts, src/formio/components/radio.ts, src/formio/components/select.ts, src/formio/components/selectboxes.ts
closes https://github.com/open-formulieren/open-forms/issues/5016 partially
=> :sparkles: [#5016] Referentielijsten dataSrc for options

src/formio/base.ts
Formio (correctly) types this as a string for how their own SDK works, which is by treating everything as a string and casting non-string values to a string before comparing it to component.conditional.eq.
However, our own builder and backend actually require the correct JSON types, e.g. a number component comparison has a number type for eq while a checkbox component reference has a boolean type. We widen the type here to match the behaviour of the builder and make it possible to implement strong typed behaviour in our own renderer.
We achieve this by removing and re-adding the property from the reference type of the Formio SDK, since extending/inheriting is not allowed (you can only narrow types that way).
=> Correctly type the conditional.eq property
